# TENSORS

In [47]:
import torch
import numpy as np

## Initializing a Tensor

In [48]:
data = [[1, 2],[3, 4]]

In [49]:
x_data = torch.tensor(data) # directly from the data

In [50]:
# from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [51]:
# initializing tensor from another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [52]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.0960, 0.2319],
        [0.3596, 0.0534]]) 



**shape** *is a tuple which determines the dimensionality of the output tensor.*

In [53]:
shape = (3,5,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7709, 0.5982, 0.1626, 0.9997, 0.0795],
        [0.2486, 0.7691, 0.4953, 0.2084, 0.0959],
        [0.9094, 0.8426, 0.6938, 0.3208, 0.5259]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


## Attributes of a Tensor

*Tensor attributes describe their shape, datatype, and the device on which they are stored.*

In [54]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

**indexing and slicing**

In [55]:
tensor = torch.ones(2, 3)
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,2] = 5
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
First row: tensor([1., 1., 1.])
First column: tensor([1., 1.])
Last column: tensor([1., 1.])
tensor([[1., 1., 5.],
        [1., 1., 5.]])


**Joining tensors**

In [56]:
t1 = torch.cat([tensor, tensor], dim=1)
print(t1)

tensor([[1., 1., 5., 1., 1., 5.],
        [1., 1., 5., 1., 1., 5.]])


**Arithmetic operations**

In [57]:
y1 = tensor @ tensor.T # ``tensor.T`` returns the transpose of a tensor
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)

torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)

torch.mul(tensor, tensor, out=z3)

tensor([[ 1.,  1., 25.],
        [ 1.,  1., 25.]])

**Single-element tensors**

In [58]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

14.0 <class 'float'>


**In-place operations**

In [59]:
print(f"{tensor} \n")
tensor.add_(5)
print("After Addition")
print(tensor)

tensor([[1., 1., 5.],
        [1., 1., 5.]]) 

After Addition
tensor([[ 6.,  6., 10.],
        [ 6.,  6., 10.]])


## Bridge with numpy

**Tensor to NumPy array**

In [60]:
t = torch.ones(4)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1.])
n: [1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.



In [61]:
t.add_(2)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3.])
n: [3. 3. 3. 3.]


**NumPy array to Tensor**

In [62]:
n = np.ones(5)
t = torch.from_numpy(n)

In [63]:
np.add(n, 5, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([6., 6., 6., 6., 6.], dtype=torch.float64)
n: [6. 6. 6. 6. 6.]
