In [1]:
import torch
import numpy as np

## Attributes of a Tensor

In [2]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

**indexing and slicing**

In [26]:
tensor = torch.ones(3, 3)
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 55
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
First row: tensor([1., 1., 1.])
First column: tensor([1., 1., 1.])
Last column: tensor([1., 1., 1.])
tensor([[ 1., 55.,  1.],
        [ 1., 55.,  1.],
        [ 1., 55.,  1.]])


**Joining tensors**

In [29]:
t1 = torch.cat([tensor, tensor], dim=1)
print(t1)

tensor([[ 1., 55.,  1.,  1., 55.,  1.],
        [ 1., 55.,  1.,  1., 55.,  1.],
        [ 1., 55.,  1.,  1., 55.,  1.]])


**Arithmetic operations**

In [34]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)

torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)

torch.mul(tensor, tensor, out=z3)

tensor([[1.0000e+00, 3.0250e+03, 1.0000e+00],
        [1.0000e+00, 3.0250e+03, 1.0000e+00],
        [1.0000e+00, 3.0250e+03, 1.0000e+00]])

**Single-element tensors**

In [35]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

171.0 <class 'float'>


**In-place operations**

In [37]:
print(f"{tensor} \n")
tensor.add_(5)
print("After Addition")
print(tensor)

tensor([[ 6., 60.,  6.],
        [ 6., 60.,  6.],
        [ 6., 60.,  6.]]) 

After Addition
tensor([[11., 65., 11.],
        [11., 65., 11.],
        [11., 65., 11.]])


## Bridge with numpy

**Tensor to NumPy array**

In [38]:
t = torch.ones(4)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1.])
n: [1. 1. 1. 1.]


In [39]:
t.add_(2)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3.])
n: [3. 3. 3. 3.]


**NumPy array to Tensor**

In [40]:
n = np.ones(5)
t = torch.from_numpy(n)

In [41]:
np.add(n, 5, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([6., 6., 6., 6., 6.], dtype=torch.float64)
n: [6. 6. 6. 6. 6.]
